# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(921, 548)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.layoutMenu = QtGui.QVBoxLayout()
        self.layoutMenu.setObjectName(_fromUtf8("layoutMenu"))
        self.groupComm = QtGui.QGroupBox(self.centralwidget)
        self.groupComm.setObjectName(_fromUtf8("groupComm"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupComm)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.layoutSerialPort = QtGui.QHBoxLayout()
        self.layoutSerialPort.setObjectName(_fromUtf8("layoutSerialPort"))
        self.lbSerialPort = QtGui.QLabel(self.groupComm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbSerialPort.sizePolicy().hasHeightForWidth())
        self.lbSerialPort.setSizePolicy(sizePolicy)
        self.lbSerialPort.setObjectName(_fromUtf8("lbSerialPort"))
        self.layoutSerialPort.addWidget(self.lbSerialPort)
        self.cbSerialPorts = QtGui.QComboBox(self.groupComm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSerialPorts.sizePolicy().hasHeightForWidth())
        self.cbSerialPorts.setSizePolicy(sizePolicy)
        self.cbSerialPorts.setObjectName(_fromUtf8("cbSerialPorts"))
        self.layoutSerialPort.addWidget(self.cbSerialPorts)
        self.verticalLayout_3.addLayout(self.layoutSerialPort)
        self.btnConnectDisconnect = QtGui.QPushButton(self.groupComm)
        self.btnConnectDisconnect.setObjectName(_fromUtf8("btnConnectDisconnect"))
        self.verticalLayout_3.addWidget(self.btnConnectDisconnect)
        self.btnStartStop = QtGui.QPushButton(self.groupComm)
        self.btnStartStop.setObjectName(_fromUtf8("btnStartStop"))
        self.verticalLayout_3.addWidget(self.btnStartStop)
        self.btnCalibrate = QtGui.QPushButton(self.groupComm)
        self.btnCalibrate.setObjectName(_fromUtf8("btnCalibrate"))
        self.verticalLayout_3.addWidget(self.btnCalibrate)
        self.layoutMenu.addWidget(self.groupComm)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layoutMenu.addItem(spacerItem)
        self.groupSinal = QtGui.QGroupBox(self.centralwidget)
        self.groupSinal.setObjectName(_fromUtf8("groupSinal"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupSinal)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lbCh0 = QtGui.QLabel(self.groupSinal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbCh0.setFont(font)
        self.lbCh0.setObjectName(_fromUtf8("lbCh0"))
        self.verticalLayout_4.addWidget(self.lbCh0)
        self.sliderCh0 = QtGui.QSlider(self.groupSinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderCh0.sizePolicy().hasHeightForWidth())
        self.sliderCh0.setSizePolicy(sizePolicy)
        self.sliderCh0.setMaximum(500)
        self.sliderCh0.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCh0.setObjectName(_fromUtf8("sliderCh0"))
        self.verticalLayout_4.addWidget(self.sliderCh0)
        self.lbThCh0 = QtGui.QLabel(self.groupSinal)
        self.lbThCh0.setObjectName(_fromUtf8("lbThCh0"))
        self.verticalLayout_4.addWidget(self.lbThCh0)
        self.sliderThCh0 = QtGui.QSlider(self.groupSinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderThCh0.sizePolicy().hasHeightForWidth())
        self.sliderThCh0.setSizePolicy(sizePolicy)
        self.sliderThCh0.setMaximum(500)
        self.sliderThCh0.setProperty("value", 100)
        self.sliderThCh0.setOrientation(QtCore.Qt.Horizontal)
        self.sliderThCh0.setObjectName(_fromUtf8("sliderThCh0"))
        self.verticalLayout_4.addWidget(self.sliderThCh0)
        self.cbCh0 = QtGui.QCheckBox(self.groupSinal)
        self.cbCh0.setEnabled(True)
        self.cbCh0.setObjectName(_fromUtf8("cbCh0"))
        self.verticalLayout_4.addWidget(self.cbCh0)
        self.lineChannels = QtGui.QFrame(self.groupSinal)
        self.lineChannels.setFrameShape(QtGui.QFrame.HLine)
        self.lineChannels.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineChannels.setObjectName(_fromUtf8("lineChannels"))
        self.verticalLayout_4.addWidget(self.lineChannels)
        self.lbCh1 = QtGui.QLabel(self.groupSinal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbCh1.setFont(font)
        self.lbCh1.setObjectName(_fromUtf8("lbCh1"))
        self.verticalLayout_4.addWidget(self.lbCh1)
        self.sliderCh1 = QtGui.QSlider(self.groupSinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderCh1.sizePolicy().hasHeightForWidth())
        self.sliderCh1.setSizePolicy(sizePolicy)
        self.sliderCh1.setMaximum(500)
        self.sliderCh1.setSingleStep(1)
        self.sliderCh1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCh1.setObjectName(_fromUtf8("sliderCh1"))
        self.verticalLayout_4.addWidget(self.sliderCh1)
        self.lbThCh1 = QtGui.QLabel(self.groupSinal)
        self.lbThCh1.setObjectName(_fromUtf8("lbThCh1"))
        self.verticalLayout_4.addWidget(self.lbThCh1)
        self.sliderThCh1 = QtGui.QSlider(self.groupSinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderThCh1.sizePolicy().hasHeightForWidth())
        self.sliderThCh1.setSizePolicy(sizePolicy)
        self.sliderThCh1.setMaximum(500)
        self.sliderThCh1.setProperty("value", 100)
        self.sliderThCh1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderThCh1.setObjectName(_fromUtf8("sliderThCh1"))
        self.verticalLayout_4.addWidget(self.sliderThCh1)
        self.cbCh1 = QtGui.QCheckBox(self.groupSinal)
        self.cbCh1.setObjectName(_fromUtf8("cbCh1"))
        self.verticalLayout_4.addWidget(self.cbCh1)
        self.layoutMenu.addWidget(self.groupSinal)
        self.horizontalLayout_2.addLayout(self.layoutMenu)
        self.layoutGraph = QtGui.QVBoxLayout()
        self.layoutGraph.setObjectName(_fromUtf8("layoutGraph"))
        self.groupComandos = QtGui.QGroupBox(self.centralwidget)
        self.groupComandos.setObjectName(_fromUtf8("groupComandos"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupComandos)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lbInstrument = QtGui.QLabel(self.groupComandos)
        self.lbInstrument.setObjectName(_fromUtf8("lbInstrument"))
        self.verticalLayout.addWidget(self.lbInstrument)
        self.cbInstruments = QtGui.QComboBox(self.groupComandos)
        self.cbInstruments.setObjectName(_fromUtf8("cbInstruments"))
        self.verticalLayout.addWidget(self.cbInstruments)
        self.line = QtGui.QFrame(self.groupComandos)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.lbNota1 = QtGui.QLabel(self.groupComandos)
        self.lbNota1.setObjectName(_fromUtf8("lbNota1"))
        self.verticalLayout.addWidget(self.lbNota1)
        self.layoutNota1 = QtGui.QHBoxLayout()
        self.layoutNota1.setObjectName(_fromUtf8("layoutNota1"))
        self.cbNota1 = QtGui.QComboBox(self.groupComandos)
        self.cbNota1.setObjectName(_fromUtf8("cbNota1"))
        self.layoutNota1.addWidget(self.cbNota1)
        self.cbEscala1 = QtGui.QComboBox(self.groupComandos)
        self.cbEscala1.setObjectName(_fromUtf8("cbEscala1"))
        self.layoutNota1.addWidget(self.cbEscala1)
        self.verticalLayout.addLayout(self.layoutNota1)
        self.lbNota2 = QtGui.QLabel(self.groupComandos)
        self.lbNota2.setObjectName(_fromUtf8("lbNota2"))
        self.verticalLayout.addWidget(self.lbNota2)
        self.layoutNota2 = QtGui.QHBoxLayout()
        self.layoutNota2.setObjectName(_fromUtf8("layoutNota2"))
        self.cbNota2 = QtGui.QComboBox(self.groupComandos)
        self.cbNota2.setObjectName(_fromUtf8("cbNota2"))
        self.layoutNota2.addWidget(self.cbNota2)
        self.cbEscala2 = QtGui.QComboBox(self.groupComandos)
        self.cbEscala2.setObjectName(_fromUtf8("cbEscala2"))
        self.layoutNota2.addWidget(self.cbEscala2)
        self.verticalLayout.addLayout(self.layoutNota2)
        self.lbNota3 = QtGui.QLabel(self.groupComandos)
        self.lbNota3.setObjectName(_fromUtf8("lbNota3"))
        self.verticalLayout.addWidget(self.lbNota3)
        self.layoutNota3 = QtGui.QHBoxLayout()
        self.layoutNota3.setObjectName(_fromUtf8("layoutNota3"))
        self.cbNota3 = QtGui.QComboBox(self.groupComandos)
        self.cbNota3.setObjectName(_fromUtf8("cbNota3"))
        self.layoutNota3.addWidget(self.cbNota3)
        self.cbEscala3 = QtGui.QComboBox(self.groupComandos)
        self.cbEscala3.setObjectName(_fromUtf8("cbEscala3"))
        self.layoutNota3.addWidget(self.cbEscala3)
        self.verticalLayout.addLayout(self.layoutNota3)
        self.layoutGraph.addWidget(self.groupComandos)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layoutGraph.addItem(spacerItem1)
        self.lbStatus = QtGui.QLabel(self.centralwidget)
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.layoutGraph.addWidget(self.lbStatus)
        self.horizontalLayout_2.addLayout(self.layoutGraph)
        self.layoutResult = QtGui.QVBoxLayout()
        self.layoutResult.setObjectName(_fromUtf8("layoutResult"))
        self.lbResult = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbResult.sizePolicy().hasHeightForWidth())
        self.lbResult.setSizePolicy(sizePolicy)
        self.lbResult.setObjectName(_fromUtf8("lbResult"))
        self.layoutResult.addWidget(self.lbResult)
        self.graphResult = QtGui.QGraphicsView(self.centralwidget)
        self.graphResult.setObjectName(_fromUtf8("graphResult"))
        self.layoutResult.addWidget(self.graphResult)
        self.horizontalLayout_2.addLayout(self.layoutResult)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MyoSound", None))
        self.groupComm.setTitle(_translate("MainWindow", "Configurações:", None))
        self.lbSerialPort.setText(_translate("MainWindow", "Porta Serial:", None))
        self.btnConnectDisconnect.setText(_translate("MainWindow", "Conectar", None))
        self.btnStartStop.setText(_translate("MainWindow", "Start", None))
        self.btnCalibrate.setText(_translate("MainWindow", "Calibrar", None))
        self.groupSinal.setTitle(_translate("MainWindow", "Sinal EMG", None))
        self.lbCh0.setText(_translate("MainWindow", "CH0: 0 V", None))
        self.lbThCh0.setText(_translate("MainWindow", "Limiar Ch0: 1 V", None))
        self.cbCh0.setText(_translate("MainWindow", "Contração", None))
        self.lbCh1.setText(_translate("MainWindow", "CH1: 0 V", None))
        self.lbThCh1.setText(_translate("MainWindow", "Limiar Ch1: 1 V", None))
        self.cbCh1.setText(_translate("MainWindow", "Contração", None))
        self.groupComandos.setTitle(_translate("MainWindow", "Comandos", None))
        self.lbInstrument.setText(_translate("MainWindow", "Instrumento", None))
        self.lbNota1.setText(_translate("MainWindow", "Nota 1", None))
        self.lbNota2.setText(_translate("MainWindow", "Nota 2", None))
        self.lbNota3.setText(_translate("MainWindow", "Nota 3", None))
        self.lbStatus.setText(_translate("MainWindow", "Status: Silencio", None))
        self.lbResult.setText(_translate("MainWindow", "Resultado:", None))

